spring:
 jpa:
  properties:
   hibernate:
    dialect: org.hibernate.dialect.PostgreSQLDialect
#
 defer-datasource-initialization: true
#
 hibernate:
  ddl-auto: update
#  show-sql: 'true'
##
 datasource:
  username: dimpetr
  password: myuser
#  url: jdbc:postgresql://localhost:5431/user_management?currentSchema=user_management
  # when you want to have an image and connect it to the db we must remove localhost
  # todo explain this to mitsos and add it through env_variables
  url: jdbc:postgresql://${USER_MANAGEMENT_DB_SERVICE_HOST}:5432/user_management?currentSchema=user_management

#  initialazation-mode: 'always'
#  initialize: 'true'
#  continue-on-error: 'true'
##
 sql:
  init:
   mode: always
   continue-on-error: true
###
logging:
 level:
  org:
   hibernate:
    type:
     descriptor:
      sql:
       BasicBinder: TRACE
#
    SQL: DEBUG
##
  springframework:
   jdbc:
    core:
     JdbcTemplate: DEBUG
     StatementCreatorUtils: TRACE
###
server:
 port: 8081
